<!DOCTYPE html>
<!-- Generated by PHPWord -->
<html>
<head>
<meta charset="UTF-8" />
<title></title>
<meta name="author" content="Michael Lewis" />
<style>
* {font-family: Arial; font-size: 11pt;}
a.NoteRef {text-decoration: none;}
hr {height: 1px; padding: 0; margin: 1em 0; border: 0; border-top: 1px solid #CCC;}
table {border: 1px solid black; border-spacing: 0px; width : 100%;}
td {border: 1px solid black;}
.Normal {text-align: left; margin-top: 0pt; margin-bottom: 0pt;}
.Body Text {font-family: 'Sylfaen'; font-size: 12pt;}
h1 {font-family: 'Sylfaen'; font-size: 30pt; font-weight: bold;}
h2 {font-family: 'Sylfaen'; font-size: 24pt; font-weight: bold;}
.List Paragraph {font-family: 'Sylfaen';}
.Table Paragraph {}
</style>
</head>
<body>
<p style="text-align: left; margin-top: 0pt;"><span style="font-size: 18pt; font-weight: bold;">Terms</span><span style="font-size: 18pt; font-weight: bold;"> </span><span style="font-size: 18pt; font-weight: bold;">and</span><span style="font-size: 18pt; font-weight: bold;"> </span><span style="font-size: 18pt; font-weight: bold;">Conditions</span><span style="font-size: 18pt; font-weight: bold;"> </span><span style="font-size: 18pt; font-weight: bold;">for</span><span style="font-size: 18pt; font-weight: bold;"> </span><span style="font-size: 18pt; font-weight: bold;">Tekavenir</span></p>
<p>&nbsp;</p>
<h1>Terms and Conditions</h1>
<p style="margin-top: 13.65pt;">Last updated: August 01, 2022</p>
<p>&nbsp;</p>
<p style="margin-top: 0; margin-bottom: 0;">Please read these terms and conditions carefully before using Our Service.</p>
<p>&nbsp;</p>
<h1>Interpretation and Definitions</h1>
<h2>Interpretation</h2>
<p style="text-align: justify; margin-top: 13.75pt;">The words in which the initial letter is capitalized have meanings defined under the followin g conditions. The following definitions shall have the same meaning regardless of whether th ey appear in singular or plural.</p>
<p>&nbsp;</p>
<h2>Definitions</h2>
<p style="margin-top: 13.8pt;">For these Terms and Conditions:</p>
<p>&nbsp;</p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt; font-weight: bold;">Affiliate</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt; font-weight: bold;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">means</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">an</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">entity</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">controlled</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">by</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">or</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">under</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">common control</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">with</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">a</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">party, wher</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">e</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> as</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">&quot;control&quot;</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">means ownership</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">of</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">50%</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">or more of</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">the</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">shares,</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">equity</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">interest,</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">or</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">other</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">s</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> ecurities entitled to vote for the election of directors or other managing authority.</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt; font-weight: bold;">Country</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt; font-weight: bold;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">refers</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">to</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">Virginia,</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">United</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">States.</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt; font-weight: bold;">Company </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">(referred</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">to</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">as</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">either</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">&quot;the Company,”</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">&quot;We,”</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">&quot;Us,&quot;</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">or</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">&quot;Our&quot;</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">in</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">this</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">Agreem</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">en</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> t) refers</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">to</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">Paramount Technology Solutions (dba Tekavenir), 2201 Cooperative Wa</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">y,</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> Ste 600, Herndon, VA 20171-3005.</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt; font-weight: bold;">Device </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">means</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">any</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">device</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">that</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">can</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">access</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">the</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">Service,</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">such</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">as</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">a</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">computer,</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">a cellphone</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">,</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> or a digital tablet.</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt; font-weight: bold;">Service</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt; font-weight: bold;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">refers</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">to</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">the</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">Website.</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt; font-weight: bold;">Terms and Conditions </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">(also</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">referred to s</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">&quot;Terms&quot;) mean these Terms and</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">Conditions</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">t</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> hat</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">form</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">the</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">entire agreement</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">between</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">You and</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">the</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">Company</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">regarding</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">the</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">use</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">of</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">th</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> e Service.</span></p>

<p>&nbsp;</p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt; font-weight: bold;">Third-party Social Media Service </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">means</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">any services</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">or</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">content (including data, info</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">r</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> mation,</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">products, or</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">services)</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">provided</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">by</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">a third party</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">that</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">may</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">be displayed,</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">incl</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">ud</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> ed, or made available by the Service.</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt; font-weight: bold;">Website</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt; font-weight: bold;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">refers</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">to</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">Tekavenir,</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">accessible</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">from</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="text-align: justify; margin-top: 0.1pt; margin-bottom: 0pt;"><a href="https://www.termsfeed.com/live/www.tekavenir.com">www.tekavenir.com</a></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt; font-weight: bold;">You </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">mean</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">the</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">individual</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">accessing</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">or</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">using</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">the</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">Service, the</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">company, or</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">other</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">legal</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">e</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> ntity</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">on</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">behalf</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">of</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">which such</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">individual</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">is</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">accessing</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">or</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">using</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">the</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">Service,</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">as applicab</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">l</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">e.</span></p>

<p>&nbsp;</p>
<h1>Acknowledgment</h1>
<p style="text-align: justify; margin-top: 13.65pt;">These are the Terms and Conditions governing this Service&#039;s use and the agreement between You and the Company. These Terms and Conditions set out the rights and obligations of all u sers regarding the use of the Service.</p>
<p>&nbsp;</p>
<p style="margin-top: 0; margin-bottom: 0;">Your access to and use of the Service is conditioned on Your acceptance of and compliance w ith these Terms and Conditions. These Terms and Conditions apply to all visitors, users, and others who are, ss or use the Service.</p>
<p>&nbsp;</p>
<p style="margin-top: 0.05pt;">You agree to be bound by these Terms and Conditions by accessing or using the Service. If Y ou disagree with any part of these Terms and Conditions, you may not access the Service.</p>
<p>&nbsp;</p>
<p style="margin-top: 0; margin-bottom: 0;">You represent that you are over the age of 18. The Company does not permit those under 18 to use the Service.</p>
<p>&nbsp;</p>
<p style="margin-top: 0; margin-bottom: 0;">Your access to and use of the Service is also conditioned on Your acceptance of and complian ce with the Company&#039;s Privacy Policy. Our Privacy Policy describes Our policies and proced ures on the collection, use, and disclosure of Your personal information when You use the A pplication or the Website and tells You about Your privacy rights and how the law protects You. Please read Our Privacy Policy carefully before using Our Service.</p>
<p>&nbsp;</p>
<h1>Links to Other Websites</h1>
<p style="margin-top: 13.6pt;">Our Service may contain links to third-party web sites websites or services not owned or con trolled by the Company.</p>
<p>&nbsp;</p>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;">The Company has no control over and assumes no responsibility for the content, privacy poli cies, or practices of any third-party websites or services. You further acknowledge and agree that the Company shall not be responsible or liable, directly or indirectly, for any damage or</p>
<p>&nbsp;</p>
<p style="margin-top: 0.45pt;">loss caused or alleged to be caused by or in connection with the use of or reliance on any suc h content, goods, or services available on or through any such web sites or services.</p>
<p>&nbsp;</p>
<p style="margin-top: 0; margin-bottom: 0;">We strongly advise You to read the terms and conditions and privacy policies of any third-pa rty web sites websites or services you visit.</p>
<p>&nbsp;</p>
<h1>Termination</h1>
<p style="margin-top: 13.6pt;">We may terminate or suspend Your access immediately, without prior notice or liability, for any reason whatsoever, including without limitation if You breach these Terms and Conditio ns.</p>
<p>&nbsp;</p>
<p style="margin-top: 0; margin-bottom: 0;">Upon termination, your right to use the Service will cease immediately.</p>
<p>&nbsp;</p>
<h1>Limitation of Liability</h1>
<p style="margin-top: 13.65pt;">Notwithstanding any damages that You might incur, the entire liability of the Company and any of its suppliers under any provision of this Terms and Your exclusive remedy for all the p receding shall be limited to the paid by You through the Service or 100 USD if You haven&#039;t p urchased anything through the Service.</p>
<p>&nbsp;</p>
<p style="margin-top: 0; margin-bottom: 0;">To the maximum extent permitted by applicable law, in no event shall the Company or its su ppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (in cluding, but not limited to, damages for loss of profits, loss of data or other information, for b usiness interruption, for personal injury, loss of privacy arising out of or in any way related t o the use of or inability to use the Service, third-party software and third-party hardware use d with the Service, or otherwise in connection with any provision of this Terms), even if the Company or any supplier has been advised of the possibility of such damages and even if the remedy fails of its essential purpose.</p>
<p>&nbsp;</p>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;">Some states do not allow the exclusion of implied warranties or limitation of liability for inci dental or consequential damages, which means that some of the above limitations may not ap ply. Each party&#039;s liability will be limited to the greatest extent permitted by law in these state s.</p>
<p>&nbsp;</p>
<h1>&quot;AS IS&quot; and &quot;AS AVAILABLE&quot; Discla</h1>
<p style="text-align: left; margin-top: 5.5pt;"><span style="font-size: 30pt; font-weight: bold;">imer</span></p>
<p style="margin-top: 13.6pt;">The Service is provided to You &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, the Company, on its behalf and half of its Affiliates and its and their respective licensors and serv ice providers, expressly disclaims all warranties, whether express, implied, statutory, or other wise, concerning the Service, including all implied warranties of merchantability, fitness for a particular purpose, title and non-infringement, and warranties that may arise out of a cours e of dealing, course of performance, usage or trade practice. Without limitation to the preced ing, the Company provides no warranty or undertaking, and makes no representation of any kind that the Service will meet Your requirements, achieve any intended results, be compati ble or work with any other software, applications, systems, or services, operate without inter ruption, meet any performance or reliability standards or be error free or that any errors or d efects can or will be corrected.</p>
<p>&nbsp;</p>
<p style="margin-top: 0; margin-bottom: 0;">Without limiting the preceding, neither the Company nor any of the company&#039;s provider pro viders makes any representation or warranty of any kind, express or implied: (i) as to the ope ration or availability of the Service, or the information, content, and materials or products in cluded thereon; (ii) that the Service will be uninterrupted or error-free; (iii) as to the accurac y, reliability, or currency of any information or content provided through the Service; or (iv) that the Service, its servers, the content, or e-mails sent from or on behalf of the Company ar e free of viruses, scripts, trojan horses, worms, malware, timebombs or other harmful compo nents.</p>
<p>&nbsp;</p>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;">Some jurisdictions do not allow the exclusion of certain types of warranties or limitations on applicable statutory rights of a consumer, so some or all of the above exclusions and limitatio ns may not apply to You. But in such a case, the exclusions and regulations outlined in this se ction shall be applied to the greatest extent enforceable under applicable law.</p>
<p>&nbsp;</p>
<h1>Governing Law</h1>
<p style="margin-top: 13.65pt;">The laws of the Country, excluding its conflicts of law rules, shall govern this Terms and You r use of the Service. Your use of the Application use may also be subject to other local, state, national, or international laws.</p>
<p>&nbsp;</p>
<h1>Disputes Resolution</h1>
<p style="margin-top: 13.6pt;">If You have any concerns or disputes about the Service, you first try to resolve the dispute informally by contacting the Company.</p>
<h1>For European Union (EU) Users</h1>
<p style="margin-top: 13.6pt;">If You are a European Union consumer, you will benefit from any mandatory provisions of t he law of the country in which you are resident inside.</p>
<p>&nbsp;</p>
<h1>The United States Legal Compliance</h1>
<p style="text-align: justify; margin-top: 13.65pt;">You represent and warrant that (i) You are not located in a country that is subject to the Unit ed States government embargo, or the United States government has designated that as a &quot;ter rorist supporting&quot; country, and (ii) You are not listed on any United States government list of prohibited or restricted parties.</p>
<p>&nbsp;</p>
<h1>Severability and Waiver</h1>
<h2>Severability</h2>
<p style="margin-top: 13.7pt;">Suppose any provision of these Terms is held to be unenforceable or invalid. In that case, suc h provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law. Any provision of these Terms is held to be unenforceable or invalid. In that case, such provision will be changed and interpreted to acco mplish the objectives of such provision to the greatest extent possible under applicable law. T he remaining provisions will continue in full force and effect.</p>
<p>&nbsp;</p>
<h2>Waiver</h2>
<p>&nbsp;</p>
<p style="text-align: justify; margin-top: 0.45pt;">Except as provided herein, the failure to exercise a right or to require performance of an obli gation under these Terms shall not affect a party&#039;s ability to exercise such right or require suc h performance at any time after that, nor shall the waiver of a breach constitute a waiver of a ny subsequent breach.</p>
<p>&nbsp;</p>
<h1>Translation Interpretation</h1>
<p style="text-align: justify; margin-top: 13.65pt;">These Terms and Conditions may have been translated if We have made them available to Y ou on our Service. You agree that the original English text shall prevail in the case of a disput e.</p>
<p>&nbsp;</p>
<h1>Changes to These Terms and Conditi ons</h1>
<p style="margin-top: 8.05pt;">We reserve the right, at Our sole discretion, At Our sole discretion we reserve modify or repl ace these Terms at any time. If a revision is material, we will make reasonable efforts to have the right before any new terms take effect. What constitutes a material change will be deter mined at Our sole discretion.</p>
<p>&nbsp;</p>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;">By continuing to access or use Our Service after those revisions become effective, you agree t o be bound by the revised terms. If You do not agree to the new terms, in whole or part, plea se stop using the website and the Service.</p>
<p>&nbsp;</p>
<h1>Contact Us</h1>
<p style="text-align: justify; margin-top: 13.6pt;">If you have any questions about these Terms and Conditions, You can contact us:</p>
<p>&nbsp;</p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">By</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">email:</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="text-align: left; margin-top: 0pt; margin-bottom: 0pt;"><a href="mailto:Info@tekavenir.com">Info@tekavenir.com</a></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">By</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">visiting</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">this</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">page</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">on</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">our</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">website: </span></p>
<p style="text-align: left; margin-top: 0pt; margin-bottom: 0pt;"><a href="http://www.tekavenir.com/contact-us">http://www.tekavenir.com/contact-</a></p>
<p style="text-align: left; margin-top: 0pt; margin-bottom: 0pt;"><a href="http://www.tekavenir.com/contact-us">us</a></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">By</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">mail:</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">2201</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">Cooperative</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">Way,</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">Ste</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">600,</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">Herndon,</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">VA</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">20171-</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">3005</span></p>

</body>
</html>
<?php /**PATH E:\laragon\www\bundler\resources\views/pdf/gMW82JCir4pmMYyhIovkqyNtPCAzqlTUI6Yp5FVG.blade.php ENDPATH**/ ?>