<!DOCTYPE html>
<!-- Generated by PHPWord -->
<html>
<head>
<meta charset="UTF-8" />
<title></title>
<meta name="author" content="Victoria Ellis" />
<style>
* {font-family: Arial; font-size: 11pt;}
a.NoteRef {text-decoration: none;}
hr {height: 1px; padding: 0; margin: 1em 0; border: 0; border-top: 1px solid #CCC;}
table {border: 1px solid black; border-spacing: 0px; width : 100%;}
td {border: 1px solid black;}
.Normal {margin-bottom: 8pt;}
.Placeholder Text {color: #808080;}
</style>
</head>
<body>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-family: 'Arial'; font-size: 12pt; font-weight: bold; text-decoration: underline ;">IN THE </span><span style="font-family: 'Arial'; font-size: 12pt; font-weight: bold; text-decoration: underline ;"> </span>						<span style="font-family: 'Arial'; font-size: 12pt; font-weight: bold; text-decoration: underline ;">Case No: </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-family: 'Arial'; font-size: 12pt; font-weight: bold; text-decoration: underline ;">EMPLOYMENT TRIBUNAL</span></p>
<p>&nbsp;</p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-family: 'Arial'; font-size: 12pt; font-weight: bold;">B</span><span style="font-family: 'Arial'; font-size: 12pt; font-weight: bold;"> </span><span style="font-family: 'Arial'; font-size: 12pt; font-weight: bold;">E</span><span style="font-family: 'Arial'; font-size: 12pt; font-weight: bold;"> </span><span style="font-family: 'Arial'; font-size: 12pt; font-weight: bold;">T</span><span style="font-family: 'Arial'; font-size: 12pt; font-weight: bold;"> </span><span style="font-family: 'Arial'; font-size: 12pt; font-weight: bold;">W</span><span style="font-family: 'Arial'; font-size: 12pt; font-weight: bold;"> </span><span style="font-family: 'Arial'; font-size: 12pt; font-weight: bold;">E</span><span style="font-family: 'Arial'; font-size: 12pt; font-weight: bold;"> </span><span style="font-family: 'Arial'; font-size: 12pt; font-weight: bold;">E</span><span style="font-family: 'Arial'; font-size: 12pt; font-weight: bold;"> </span><span style="font-family: 'Arial'; font-size: 12pt; font-weight: bold;">N:-</span></p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p style="text-align: right; margin-top: 0; margin-bottom: 0;"><span style="font-family: 'Arial'; font-size: 12pt; font-weight: bold; text-decoration: underline ;">C</span><span style="font-family: 'Arial'; font-size: 12pt; font-weight: bold; text-decoration: underline ;">laimant</span></p>
<p>&nbsp;</p>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: 'Arial'; font-size: 12pt; font-weight: bold;">-and-</span></p>
<p>&nbsp;</p>
<p style="text-align: right; margin-top: 0; margin-bottom: 0;"><span style="font-family: 'Arial'; font-size: 12pt; font-weight: bold; text-decoration: underline ;">Respondent</span></p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<table class="TableGrid">
<tr>
<td>
<p>&nbsp;</p>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: 'Arial'; font-size: 12pt; font-weight: bold;">INDEX TO HEARING BUNDLE</span></p>
<p>&nbsp;</p>
</td>
</tr>
</table>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
</body>
</html>
<?php /**PATH D:\laragon\www\bundler\resources\views/pdf/8yYMr8a8z9hMGj2q7rRGOp42U3i88Q5CUaeTyaoy.blade.php ENDPATH**/ ?>