<!DOCTYPE html>
<!-- Generated by PHPWord -->
<html>
<head>
<meta charset="UTF-8" />
<title></title>
<meta name="author" content="Michael Lewis" />
<style>
* {font-family: Arial; font-size: 11pt;}
a.NoteRef {text-decoration: none;}
hr {height: 1px; padding: 0; margin: 1em 0; border: 0; border-top: 1px solid #CCC;}
table {border: 1px solid black; border-spacing: 0px; width : 100%;}
td {border: 1px solid black;}
.Normal {text-align: left; margin-top: 0pt; margin-bottom: 0pt;}
.Body Text {font-family: 'Arial'; font-size: 8.5pt;}
h1 {font-family: 'Arial'; font-size: 22.5pt;}
h2 {font-family: 'Arial'; font-size: 18pt;}
h3 {font-family: 'Arial'; font-size: 13.5pt;}
.List Paragraph {font-family: 'Arial';}
.Table Paragraph {}
</style>
</head>
<body>
<h1>Privacy Policy for Tekavenir</h1>
<p style="margin-top: 10pt;">This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
<p style="margin-top: 0; margin-bottom: 0;">We use Your data to provide and improve the Service. By using the Service, you agree to the collection and use of information by this Privacy Policy. This Privacy Policy has been created with the help of the Terms Feed Privacy Policy Generator.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<h1>Interpretation and Definitions</h1>
<p>&nbsp;</p>
<h2>Interpretation</h2>
<p style="margin-top: 0; margin-bottom: 0;">The words in which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear singular or plural.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<h2>Definitions</h2>
<p style="margin-top: 0.45pt;">For this Privacy Policy:</p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">A</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">ccount means an individual account created for You to access our Service or parts of our Service. Company</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">(referred</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">to</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">as</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">either &quot;the</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">Company,” &quot;We,”</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">&quot;Us,&quot; or &quot;Our&quot; in</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">this</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">Agreement) refers to</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">Tekavenir,</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt; color: #393939;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt; color: #393939;">2201 Cooperative Way, Ste 600, Herndon, VA</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt; color: #393939;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt; color: #393939;">20171-3005</span></p>

<p style="text-align: left; margin-top: 0pt;"><span style="font-family: 'Symbol'; font-size: 10pt;"></span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">C</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">ookies are small files placed on Your computer, mobile device, or any other device by a website, containing</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">the details of Your browsing history on that website among its many</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">uses.</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">C</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">ountry refers to Virginia, United</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">States.</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">D</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">evice means any device that can access the Service, such as a computer, a cellphone, or a digital</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">tablet.</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">P</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">ersonal Data is any information that relates to an identified or identifiable</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">individual.</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">S</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">ervice refers to the Website.</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">S</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">ervice Provider means any natural or legal person who processes the data on behalf</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service, </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">or </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">to assist the Company in analyzing how the Service is</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">used.</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">T</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">hird-party</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">Social Media</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">Service</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">refers</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">to</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">any</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">website</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">or social network</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">website</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">through</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">which</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">a</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">User</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">can</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">log</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">in or create an account to use the</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">Service.</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">U</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">sage Data refers to data collected automatically, either generated by the Service or from the</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">Service infrastructure (for example, the duration of a page</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">visit).</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">Webs</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">ite refers to TAP Rideshare, accessible from</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="text-align: left; margin-top: 5.1pt; margin-bottom: 0pt;"><a href="http://www.tekavenir.com/">www.tekavenir.com</a></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">Y</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">ou mean the individual accessing or using the Service, the company, or other legal entity on behalf of which such individual is accessing or using the Service, as</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">applicable.</span></p>

<p>&nbsp;</p>
<h1>Collecting and Using Your Personal Data</h1>
<h2>Types of Data Collected</h2>
<h3>Personal Data</h3>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;">While using Our Service, we may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally, identifiable information may include, but is not limited to:</p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">•</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;"> Email</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">address</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">•</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;"> First name and last</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">name</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">•</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;"> Phone number</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">•</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;"> Address, State, Province, ZIP/Postal code,</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">City</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">•</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;"> Usage</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">Data</span></p>

<h3>Usage Data</h3>
<p style="text-align: justify; margin-top: 0.45pt;">Usage Data has collected automatically when using the Service.</p>
<p style="text-align: justify; margin-top: 0.2pt;">Usage Data may include information such as Your Device&#039;s Internet Protocol address (e.g., IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;">When You access the Service by or through a mobile device, we may collect certain information automatically, including, but not limited to, the type of mobile device You use, your mobile device&#039;s unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;">We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<h3>Information from Third-Party Social Media Services</h3>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;">The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:</p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">•</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;"> Google</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">•</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;"> Facebook</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">•</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">Twitter</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">•</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">LinkedIn</span></p>

<p style="margin-top: 8.1pt;">Suppose You decide to register through or otherwise grant us access to a Third-Party Social Media Service. In that case, we may collect Personal data associated with Your Third-Party Social Media Service&#039;s account, such as Your name, email address, activities, or contact list associated with that account.</p>
<p style="margin-top: 0; margin-bottom: 0;">You may also share additional information with the Company through Your Third-Party Social Media Service&#039;s account. Suppose You choose to provide such information and Personal Data during registration or otherwise. In that case, you are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<h3>Tracking Technologies and Cookies</h3>
<p style="margin-top: 0; margin-bottom: 0;">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies are beacons, tags, and scripts to collect and track information and improve and analyze Our Service. The technologies We use may include:</p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">C</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">ookies or Browser Cookies. A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a cookie is being sent. However, if You do not accept Cookies, you may</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">not be able to use some parts of our Service. Unless you have adjusted Your browser setting so it will refuse cookies, our Service may use</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">Cookies.</span></p>

<p>&nbsp;</p>
<p style="margin-top: 0; margin-bottom: 0;">	</p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">F</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">lash</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">Cookies.</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">Certain</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">features</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">of</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">our</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">Service</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">may</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">use</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">local</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">stored</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">objects</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">(or</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">Flash</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">Cookies)</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">to</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">collect</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">and</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">store information about Your preferences </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">or</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">activity on our Service. Flash Cookies are not managed by the same</span></p>

<p>&nbsp;</p>
<p style="margin-top: 4.05pt;">browser settings as those used for Browser Cookies. For more information on how to delete Flash Cookies, please read &quot;Where can I change the settings for disabling or deleting local shared objects?&quot; available at https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects- flash.html#main_Where_can_I_change_the_settings_for_disabling<span style="text-decoration: underline ;"> </span>or_deleting_local_shared_objects_.</p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">Web</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> Beacons. Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">users</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">who</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">have</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">visited</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">those</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">pages</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">or</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">opened</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">an</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">email</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">and</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">for</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">other related</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">website</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">statistics</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">(for</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">example, recording the popularity of a specific section and verifying system and server</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">integrity).</span></p>

<p>&nbsp;</p>
<p style="margin-top: 0.05pt;">Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. You can learn more about cookies on the Terms Feed website article.</p>
<p style="margin-top: 0.35pt;">We use both Sessions and Persistent Cookies for the purposes set out below:</p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">N</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">ecessary / Essential</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">Cookies</span></p>

<p style="margin-top: 9.8pt;">Type: Session Cookies Administered by: Us</p>
<p style="margin-top: 0; margin-bottom: 0;">Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use</p>
<p style="margin-top: 0; margin-bottom: 0;">some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the</p>
<p style="margin-top: 0.25pt;">The services you have asked for cannot be provided, and We only use these Cookies to offer you those services.</p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">C</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">ookies Policy / Notice Acceptance</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">Cookies</span></p>

<p style="margin-top: 8.35pt;">Type: Persistent Cookies Administered by: Us</p>
<p style="margin-top: 0.2pt;">Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">F</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">unctionality</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">Cookies</span></p>

<p style="margin-top: 8.35pt;">Type: Persistent Cookies Administered by: Us</p>
<p style="margin-top: 0; margin-bottom: 0;">Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your</p>
<p style="margin-top: 0; margin-bottom: 0;">login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time. You use the Website.</p>
<p style="margin-top: 0; margin-bottom: 0;">For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<h2>Use of Your Personal Data</h2>
<p style="margin-top: 0.45pt;">The Company may use Personal Data for the following purposes:</p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">T</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">o provide and maintain our Service, including monitoring the usage of our</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">Service.</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">T</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">o manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">give</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">You</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">access</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">to</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">different functionalities</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">of</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">the</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">Service</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">that</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">are</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">available</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">to</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">You</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">as</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">a</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">registered</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">user.</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">F</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">or</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">the</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">performance</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">of</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">a</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">contract:</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">the</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">development,</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">compliance,</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">and</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">undertaking</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">of</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">the</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">purchase</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">contract</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">for the products,</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">items,</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">or</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">services</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">You</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">have</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">purchased</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">or</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">of</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">any</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">other</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">contract</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">with</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">Us</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">through</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">the</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">Service.</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">T</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">o contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication,</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">such</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">as</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">a</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">mobile</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">application&#039;s</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">push</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">notifications</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">regarding</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">updates</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">or</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">informative</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">communications related to the functionalities, products, or contracted services, including the security updates, when necessary or reasonable for their</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">implementation.</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">T</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">o provide You with news, special offers, and general information about other goods, services, and events that we offer that are like those that you have already purchased or enquired about unless You have opted not to receive such</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">information.</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">T</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">o manage Your requests: To attend and manage Your requests to</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">Us.</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">F</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">or business transfers: We may use Your information to evaluate </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">or </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">conduct a merger, divestiture, restructuring, reorganization, dissolution, or another sale or transfer of some or all of Our assets, whether as a going concern or as part </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">of </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">transferred.</span></p>

<p>&nbsp;</p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">F</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">or other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns, and evaluating and improving our Service, products, services, marketing, and your</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">experience.</span></p>

<p>&nbsp;</p>
<p style="margin-top: 0; margin-bottom: 0;">We may share Your personal information in the following situations:</p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">W</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">ith Service Providers: We may transfer Your personal information with Service Providers to monitor</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">and analyze the use of our Service to contact</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">You.</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">F</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">or business transfers: We may share or transfer Your personal information in connection with, or during negotiations</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">of,</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">any</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">merger,</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">sale</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">of</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">Company</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">assets,</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">financing,</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">or acquisition</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">of</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">all</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">or</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">a</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">portion</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">of Our business</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">to another</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">company.</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">W</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">ith Affiliates: We may share Your information with Our affiliates, which will require those affiliates to honor</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">this Privacy Policy. Affiliates include Our</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">parents.</span></p>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">C</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">ompany and any other subsidiaries, joint venture partners, or companies that We control or are under</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">common control with</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">Us.</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">W</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">ith</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">business</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">partners:</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">We</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">may</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">share</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">Your information</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">with</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">Our</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">business</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">partners</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">to</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">offer</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">You</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">certain</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">products, services, or</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">promotions.</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">W</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">ith other users: when You share personal information or otherwise interact in public areas, such information</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">may be viewed by all users and publicly distributed outside. If You interact with other users </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">or </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">register through a Third- Party Social Media Service, your contacts on the Third-Party Social Media Service may see Your name, profile, pictures, and description of Your activity. Similarly, other users can view your activity reports, communicate with You, and view Your</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">profile.</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">W</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">ith Your consent: We may disclose Your personal information for any other</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">purpose.</span></p>

<h2>Retention of Your Personal Data</h2>
<p style="margin-top: 0; margin-bottom: 0;">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
<p style="margin-top: 0.25pt;">The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or improve the functionality of Our Service. We are legally obligated to retain this data for extended periods.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<h2>Transfer of Your Personal Data</h2>
<p style="margin-top: 0; margin-bottom: 0;">Your information, including Personal Data, is processed at the Company&#039;s operating offices and in any other places where the parties involved in the processing are located. It means</p>
<p style="margin-top: 0; margin-bottom: 0;">that this information may be transferred to — and maintained on — computers located outside of Your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those from Your authority. Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;">The Company will take all necessary steps to ensure that Your data is treated securely and by this Privacy Policy, and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place, including the security of Your data and other personal information.</p>
<p>&nbsp;</p>
<h2>Disclosure of Your Personal Data</h2>
<h3>Business Transactions</h3>
<p style="margin-top: 0; margin-bottom: 0;">If the Company is involved in a merger, acquisition, or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and subject to a different Privacy Policy.</p>
<p>&nbsp;</p>
<h3>Law enforcement</h3>
<p style="margin-top: 0; margin-bottom: 0;">Under certain circumstances, the Company may be required to disclose Your Data if required by law or in response to valid requests by public authorities (e.g., a court or a government agency).</p>
<p>&nbsp;</p>
<h3>Other legal requirements</h3>
<p style="margin-top: 0.4pt;">The Company may disclose Your Data in the good faith belief that such action is necessary to:</p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">C</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">omply with a legal</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">obligation</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">Pr</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">otect and defend the rights or property of the</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">Company</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">Pr</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">event or investigate possible wrongdoing in connection with the</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">Service</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">Pr</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">otect the personal safety of Users of the Service or the</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">public</span></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">P</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">rotect against legal</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;"> </span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 8.5pt;">liability</span></p>

<h2>Security of Your Personal Data</h2>
<p style="margin-top: 0; margin-bottom: 0;">The security of Your Personal Data is essential to Us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, we cannot guarantee its absolute security.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<h1>Children&#039;s Privacy</h1>
<p style="margin-top: 0.05pt;">Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under 13. If You are a parent or guardian and know that Your child has provided Us with Personal Data, please get in touch with Us. Suppose We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent. In that case, we take steps to remove that information from Our servers.</p>
<p style="margin-top: 0; margin-bottom: 0;">If We need to rely on consent as a legal basis for processing Your information and Your country requires permission from a parent, we may require Your parent&#039;s consent before We collect and use that information.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<h1>Links to Other Websites</h1>
<p style="margin-top: 0; margin-bottom: 0;">Our Service may contain links to other websites not operated by Us. If You click on a third-party link, you will be directed to that third party&#039;s site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
<p style="margin-top: 0; margin-bottom: 0;">We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or</p>
<p style="margin-top: 0.5pt;">services.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<h1>Changes to this Privacy Policy</h1>
<p style="margin-top: 0.05pt;">We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
<p style="margin-top: 0; margin-bottom: 0;">We will inform you via email and a prominent notice on Our Service before the change becomes effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.</p>
<p style="margin-top: 0; margin-bottom: 0;">You are advised to review this Privacy Policy periodically for any changes. These Privacy Policy changes are effective when posted on this page.</p>
<p>&nbsp;</p>
<h1>Contact Us</h1>
<p style="margin-top: 0.5pt;">If you have any questions about this Privacy Policy, you can contact us:</p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">By</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;"> email:</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;"> </span></p>
<p style="text-align: left; margin-top: 0.2pt; margin-bottom: 0pt;"><a href="mailto:info@tekavenir.com">info@tekavenir.com</a></p>

<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;">By</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;"> visiting this page on our website:</span></p>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 7.5pt;"> </span></p>
<p style="text-align: left; margin-top: 4.75pt; margin-bottom: 0pt;"><a href="http://www.tekavenir.com/contact-us">http://www.tekavenir.com/contact-us</a></p>

</body>
</html>
<?php /**PATH E:\laragon\www\bundler\resources\views/pdf/jL8Uada2rbhfP7zPANwuzmhvtiEKwXUqyBqajYBM.blade.php ENDPATH**/ ?>