<!DOCTYPE html>
<!-- Generated by PHPWord -->
<html>
<head>
<meta charset="UTF-8" />
<title></title>
<meta name="author" content="Sk" />
<style>
* {font-family: Arial; font-size: 11pt;}
a.NoteRef {text-decoration: none;}
hr {height: 1px; padding: 0; margin: 1em 0; border: 0; border-top: 1px solid #CCC;}
table {border: 1px solid black; border-spacing: 0px; width : 100%;}
td {border: 1px solid black;}
.Normal {margin-bottom: 10pt;}
.Hyperlink {color: #0000FF; text-decoration: underline ;}
.No Spacing {margin-bottom: 0pt;}
</style>
</head>
<body>
<p style="margin-top: 0; margin-bottom: 0;"><a href="https://shopdigital.2spice.link/">https://shopdigital.2spice.link/</a></p>
<p>&nbsp;</p>
<p style="margin-top: 0; margin-bottom: 0;">hostinger</p>
<p>&nbsp;</p>
<p style="margin-top: 0; margin-bottom: 0;">2spice22@gmail.com</p>
<p style="margin-top: 0; margin-bottom: 0;">Spice45@&amp;</p>
<p style="margin-top: 0; margin-bottom: 0;">art.2spice.link</p>
<p>&nbsp;</p>
<p style="margin-top: 0; margin-bottom: 0;">****</p>
<p style="margin-top: 0; margin-bottom: 0;">Website hobe upcoming musician der jonno<br />
ekta menu thakbe tader talent and comedy show korar jonno</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p style="margin-top: 0; margin-bottom: 0;">User can login their profile and post music audio/video, talent and comedy. each will have a separate menu. </p>
<p style="margin-top: 0; margin-bottom: 0;">user get paid per like on their post with native crypto token. </p>
<p style="margin-top: 0; margin-bottom: 0;">website should also be based on region. user can select country and post. </p>
<p>&nbsp;</p>
<p style="margin-top: 0; margin-bottom: 0;">people can comment and share their post on other social media. website view like netflix.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p style="margin-top: 0; margin-bottom: 0;">Note: User ekbar e like dite parbe spam remove korar jonno captcha rakha jete pare.</p>
<p style="margin-top: 0; margin-bottom: 0;">Website e sudhu music na. two other menu thkabe to post your talent and comedy.</p>
<p style="margin-top: 0; margin-bottom: 0;">user can post base on their region. they will select their country.</p>
<p style="margin-top: 0; margin-bottom: 0;">posting page netflix er moto dekhte hobe.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
</body>
</html>
<?php /**PATH D:\laragon\www\bundler\resources\views/pdf/grmCGA64nUCJ4oxr1qC3AcGrFbImLvNXeosbARNy.blade.php ENDPATH**/ ?>