<!DOCTYPE html>
<!-- Generated by PHPWord -->
<html>
<head>
<meta charset="UTF-8" />
<title></title>
<meta name="author" content="Oni" />
<style>
* {font-family: Arial; font-size: 11pt;}
a.NoteRef {text-decoration: none;}
hr {height: 1px; padding: 0; margin: 1em 0; border: 0; border-top: 1px solid #CCC;}
table {border: 1px solid black; border-spacing: 0px; width : 100%;}
td {border: 1px solid black;}
.Normal {margin-bottom: 10pt;}
</style>
</head>
<body>
<p style="margin-top: 0; margin-bottom: 0;">Installing Meteor on Windows:</p>
<p style="margin-top: 0; margin-bottom: 0;">======================================</p>
<p style="margin-top: 0; margin-bottom: 0;">Step 1: Install node 8.8.1</p>
<p style="margin-top: 0; margin-bottom: 0;">https://nodejs.org/ru/blog/release/v8.8.1/</p>
<p>&nbsp;</p>
<p style="margin-top: 0; margin-bottom: 0;">Step 2: Install Choco using below command (run as an admin)</p>
<p>&nbsp;</p>
<p style="margin-top: 0; margin-bottom: 0;">@&quot;%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe&quot; -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command &quot;[System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString(&#039;https://chocolatey.org/install.ps1&#039;))&quot; &amp;&amp; SET &quot;PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin&quot;</p>
<p>&nbsp;</p>
<p style="margin-top: 0; margin-bottom: 0;">Step 3: Install Meteor </p>
<p style="margin-top: 0; margin-bottom: 0;">choco install meteor --release 1.6</p>
<p>&nbsp;</p>
<p style="margin-top: 0; margin-bottom: 0;">Step 4: Extract/clone the VS1 project</p>
<p>&nbsp;</p>
<p style="margin-top: 0; margin-bottom: 0;">Step 5: Extract the Node Modules</p>
<p>&nbsp;</p>
<p style="margin-top: 0; margin-bottom: 0;">Step 6: Put the .bat file outside of the vs1 project folder. Just click on it to run the project. No command needed.</p>
</body>
</html>
<?php /**PATH D:\laragon\www\bundler\resources\views/pdf/wpzNrOBojNLk67q87yOPpcEEqIB9U7yweDiQjFGO.blade.php ENDPATH**/ ?>